function logo(compactMode=false){return `<div class="brand"><img class="logo-img" src="logo.png" alt="HED" onerror="if(!this.dataset.tried){this.dataset.tried='1';this.src='Logo.jpeg'}else{this.style.display='none';this.nextElementSibling.style.display='grid'}"><div class="logo-fallback" style="display:none">HED</div>${compactMode?'':`<div><div class="brand-title">Honest Estate Developers</div><div class="brand-sub">Property Operations</div></div>`}</div>`}
function searchIndex(q=''){q=q.trim().toLowerCase();let all=[...state.tenants.map(t=>({type:'Tenant',icon:'◎',label:t.business,meta:`${uBy(t.unitId)?.number||'No unit'} · ${t.contact}`,page:'tenants',param:t.id,keys:`${t.business} ${t.contact} ${t.email} ${t.phone} ${uBy(t.unitId)?.number||''}`})),...state.units.map(u=>({type:'Shop',icon:'▦',label:`Shop ${u.number}`,meta:`${u.level} · ${u.size} m² · ${u.status}`,page:'units',param:u.id,keys:`${u.number} ${u.level} ${u.status}`})),...state.invoices.map(i=>({type:'Invoice',icon:'₵',label:i.id,meta:`${tBy(i.tenantId)?.business} · ${fmt(i.balance)} balance`,page:'invoices',param:null,keys:`${i.id} ${tBy(i.tenantId)?.business||''}`})),...state.receipts.map(r=>({type:'Receipt',icon:'▥',label:r.id,meta:`${tBy(r.tenantId)?.business} · ${fmt(r.amount)}`,page:'receipts',param:null,keys:`${r.id} ${r.reference} ${tBy(r.tenantId)?.business||''}`})),...state.leases.map(l=>({type:'Lease',icon:'▧',label:l.id,meta:`${tBy(l.tenantId)?.business} · ${uBy(l.unitId)?.number}`,page:'leases',param:l.id,keys:`${l.id} ${tBy(l.tenantId)?.business||''} ${uBy(l.unitId)?.number||''}`}))];return all.filter(x=>!q||x.keys.toLowerCase().includes(q)).slice(0,10)}
function searchRows(items){return items.map(x=>`<div class="command-row" onclick="closeModal();go('${x.page}'${x.param?`,'${x.param}'`:''})"><div class="command-icon">${x.icon}</div><div style="flex:1"><b>${x.label}</b><span>${x.meta}</span></div><span class="chip gray">${x.type}</span></div>`).join('')||`<div class="muted" style="padding:18px;text-align:center">No matching HED records found.</div>`}
function openSearch(){modal('Search HED Property System',`<div class="search-modal"><div style="display:flex;gap:8px;align-items:center;border-bottom:1px solid var(--line);padding-bottom:10px"><span>⌕</span><input id="globalSearch" autofocus placeholder="Search shop, tenant, lease, invoice, receipt..." oninput="filterSearch(this.value)"></div><div id="searchResults" style="margin-top:8px">${searchRows(searchIndex())}</div><div class="demo-note">Tip: search “ABC”, “G-014”, “LEASE-2026”, an invoice number or payment reference.</div></div>`);setTimeout(()=>document.getElementById('globalSearch')?.focus(),50)}
function filterSearch(q){document.getElementById('searchResults').innerHTML=searchRows(searchIndex(q))}
function openNotifications(){let allowed=state.notifications.filter(n=>{let nav=NAV.find(x=>x[0]===n.page);return !nav||nav[3].includes(user.role)});state.notifications.forEach(n=>{if(allowed.includes(n))n.read=true});save();modal('Notifications',allowed.length?allowed.map(n=>`<div class="command-row" onclick="closeModal();go('${n.page}')"><div class="command-icon">◇</div><div><b>${n.title}</b><span>${n.detail} · ${n.time}</span></div></div>`).join(''):`<div class="good-box"><b>No new role-relevant notifications</b><div class="section-sub">Your workspace is currently clear.</div></div>`)}
function openProfile(){modal(user.name,`<div class="row-between"><div><div class="label">Role</div><b style="font-size:12px">${user.title}</b><div class="section-sub">${user.email}</div></div><div class="avatar">${initials(user.name)}</div></div><button class="btn btn-danger" style="width:100%;margin-top:16px" onclick="closeModal();logout()">Sign out</button>`)}
function togglePresentation(){presentation=!presentation;document.body.classList.toggle('presentation',presentation);toast('Presentation mode '+(presentation?'enabled':'disabled'),presentation?'Navigation chrome reduced for stakeholder demos.':'Standard working view restored.');renderApp(false)}
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeModal()});window.addEventListener('hashchange',()=>{let h=location.hash.replace('#','').split('/');if(h[0]){currentPage=h[0];pageParam=h[1]||null;if(user)renderApp(false)}});
(function start(){if(user){let h=location.hash.replace('#','').split('/');if(h[0]){currentPage=h[0];pageParam=h[1]||null}else currentPage=user.role==='tenant'?'tenant-portal':'dashboard';renderApp(true)}else loginView()})();
